# Develop override settings

url: http://localhost:4000

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "sunrise"
